Vagrant.configure("2") do |config|
  config.vm.box = "#{ENV['DISTR']}/#{ENV['OS']}"
  config.vm.hostname = "host4test"

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider "virtualbox" do |vb|
    vb.memory = ENV['RAM'] || "4096"
    vb.cpus = ENV['CPU'] || "2"
    vb.customize ["modifyvm", :id, "--ioapic", "on"]
  end

  config.vm.provision "shell", inline: <<-SHELL
    set -e
    curl -O https://download.onlyoffice.com/docs/docs-enterprise-install.sh
    chmod +x docs-enterprise-install.sh
    printf "n\\n" | sudo bash docs-enterprise-install.sh
  SHELL
end
