name: Compile from source

on:
  workflow_dispatch:

jobs:
  test-compilation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: clone repo
        run: git clone https://github.com/ONLYOFFICE/build_tools.git -b ${{ vars.ONLYOFFICE_BUILDTOOLS_BRANCH }}

      - name: Compile from source
        run: |
          cd build_tools
          mkdir out
          sudo docker build --tag onlyoffice-document-editors-builder .
          docker run -v $PWD/out:/build_tools/out onlyoffice-document-editors-builder