name: dev OracleDB load test

on:
  workflow_dispatch:

jobs:
  oracle-test:
    runs-on: ubuntu-latest
    services:
      oracledb:
        image: gvenzl/oracle-xe:21-slim
        env:
          ORACLE_PASSWORD: admin
          ORACLE_DATABASE: onlyoffice
          APP_USER: onlyoffice
          APP_USER_PASSWORD: onlyoffice
        ports:
          - 1521:1521
      onlyoffice:
        image: onlyoffice/4testing-documentserver-ee:${{ vars.ONLYOFFICE_DOCKER_VERSION }}
        env:
          DB_TYPE: oracle
          DB_HOST: oracledb
          DB_PORT: 1521
          DB_NAME: onlyoffice
          DB_USER: onlyoffice
          DB_PWD: onlyoffice
        ports:
          - 80:80
          - 443:443

    steps:
      - uses: actions/checkout@v4

      - name: Run tests in a container
        run: |
          docker run --rm \
            --network ${{ job.services.onlyoffice.network }} \
            curlimages/curl:8.9.1 \
            curl -vk http://onlyoffice