name: Update version in README

on:
  schedule:
    - cron: '0 11 * * 3'  # Wednesday 14:00 Moscow time (UTC+3)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Update version badge in README.md
        run: |
          VERSION="v${{ vars.ONLYOFFICE_DEV_VERSION }}-${{ vars.ONLYOFFICE_DEV_BUILD }}"
          FILE="README.md"
          START="<!-- onlyoffice-version-start -->"
          END="<!-- onlyoffice-version-end -->"

          CURRENT=$(grep -oP "$START\K.*?(?=$END)" "$FILE")
          echo "Current: $CURRENT | Target: $VERSION"

          if [ "$CURRENT" != "$VERSION" ]; then
            echo "Updating version..."
            sed -i "s|\($START\).*\($END\)|\1$VERSION\2|" "$FILE"
            git config user.name "github-actions"
            git config user.email "actions@github.com"
            git add README.md
            git commit -m "[Update version in README] $VERSION"
            git push
          else
            echo "Version is up to date, skipping."
          fi
