name: test

on:
  workflow_dispatch:

jobs:
  debian11:
    name: Test Docs with Debian 11
    runs-on: ubuntu-latest
    steps:
      - run: echo test

  debian12:
    name: Test Docs with Debian 12
    runs-on: ubuntu-latest
    steps:
      - run: ./test.sh1

  rhel9:
    name: Test Docs with RHEL 9
    runs-on: ubuntu-latest
    steps:
      - run: echo test